version: "3.7"
services:
    app:
        build:
            context: .
        container_name: app_to_do
        working_dir: /app
        ports:
            - "8181:8181"
        volumes:
            - ./:/app
        networks:
            - app_to_do
networks:
    app_to_do:
        driver: bridge
